config/routes.rb
Rails.application.routes.draw do
  get  '/signup',  to: 'users#new'
  resources :users
  get 'welcome/index'
  resources :peeps
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/peep.rb
class Peep < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_save { email.downcase! }

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/peeps_controller.rb
class PeepsController < ApplicationController
  def index
    @peeps = Peep.all
  end

  def new
  end

  def create
    @peep = Peep.new(peep_params)
    @peep.save
    redirect_to @peep
  end

  def show
    @peep = Peep.find(params[:id])
  end

private
  def peep_params
    params.require(:peep).permit(:text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
     @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
    else
      render 'new'
    end
    redirect_to :peeps
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peeps_helper.rb
module PeepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peeps/index.html.erb
<table>
  <tr>
    <th>Peeps</th>
  </tr>

  <% @peeps.each do |peep| %>
    <tr>
      <td><%= peep.text %></td>
      <td><%= link_to 'Show', peep_path(peep) %></td>
    </tr>
  <% end %>
</table>

app/views/peeps/new.html.erb
<h1>New Peep</h1>
<%= form_for :peep, url: peeps_path do |f| %>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/peeps/show.html.erb
<p>
  <strong>Text:</strong>
  <%= @peep.text %>
</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>CHITTER</h1>